"""models v1

Revision ID: 46b13acaa127
Revises: bd72db48fea5
Create Date: 2026-01-23 23:50:20.990790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b13acaa127'
down_revision: Union[str, Sequence[str], None] = 'bd72db48fea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=2), nullable=False, comment='Source of supply: RU or CN'),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplies_source'), 'supplies', ['source'], unique=False)
    op.create_index(op.f('ix_supplies_status'), 'supplies', ['status'], unique=False)
    op.create_index(op.f('ix_supplies_supplier_id'), 'supplies', ['supplier_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_final', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_product_id'), 'batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_batches_supply_id'), 'batches', ['supply_id'], unique=False)
    op.create_index(op.f('ix_batches_warehouse_id'), 'batches', ['warehouse_id'], unique=False)
    op.create_table('supply_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('places_count', sa.Integer(), nullable=True),
    sa.Column('dest_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dest_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_events_dest_warehouse_id'), 'supply_events', ['dest_warehouse_id'], unique=False)
    op.create_index(op.f('ix_supply_events_event_type'), 'supply_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_supply_events_supply_id'), 'supply_events', ['supply_id'], unique=False)
    op.create_table('supply_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('unit_price_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_items_product_id'), 'supply_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_supply_items_supply_id'), 'supply_items', ['supply_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_items_supply_id'), table_name='supply_items')
    op.drop_index(op.f('ix_supply_items_product_id'), table_name='supply_items')
    op.drop_table('supply_items')
    op.drop_index(op.f('ix_supply_events_supply_id'), table_name='supply_events')
    op.drop_index(op.f('ix_supply_events_event_type'), table_name='supply_events')
    op.drop_index(op.f('ix_supply_events_dest_warehouse_id'), table_name='supply_events')
    op.drop_table('supply_events')
    op.drop_index(op.f('ix_batches_warehouse_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_supply_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_product_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_supplies_supplier_id'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_status'), table_name='supplies')
    op.drop_index(op.f('ix_supplies_source'), table_name='supplies')
    op.drop_table('supplies')
    # ### end Alembic commands ###
